# ruff.toml

line-length = 88
target-version = "py312"

[lint]
select = ["E", "F", "I"]  # basic errors, formatting, imports
ignore = ["E501"]          # ignore line length errors if desired
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
