version: "3.9"

services:
  zenml:
    image: zenmldocker/zenml-server:0.91.0
    ports:
      - "8080:8080"
    env_file: docker/server/zenml-server.env
    volumes:
      - ~/.aws:/home/zenml/.aws:ro
      # for some reason, these do not work:
      # ZENML_DEFAULT_USER_NAME: zenml
      # ZENML_DEFAULT_USER_PASSWORD: password
      # Use "default" and "" as username and password, respectively
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure